language: node_js
node_js:
  - "9"
dist: trusty
sudo: false
cache: npm
notifications:
  email:
    on_success: never
before_deploy:
  - npm run build

deploy:
  - provider: s3
    bucket: ${BUCKET_NAME}
    region: ap-northeast-1
    endpoint: ${BUCKET_NAME}.s3-ap-northeast-1.amazonaws.com
    skip_cleanup: true
    local-dir: dist
    on:
      branch: env/prod
